#!/bin/bash

# Based on this tutorial, with a few minor changes:
# https://www.codementor.io/tamizhvendan/beginner-guide-setup-reactjs-environment-npm-babel-6-webpack-du107r9zr

# Globals
dev_directory="/path/to/your/development/directory"

index_html="
<html>
  <head>
    <meta charset='utf-8'>
    <title>React.js using NPM, Babel6 and Webpack</title>
  </head>
  <body>
    <div id='app' />
    <script src='public/bundle.js' type='text/javascript'></script>
  </body>
</html>
"

index_jsx="
import React from 'react';
import {render} from 'react-dom';
class App extends React.Component {
  render () {
    return <p> Hello React!</p>;
  }
}
render(<App/>, document.getElementById('app'));
"

webpack_config="
var webpack = require('webpack');
var path = require('path');
var BUILD_DIR = path.resolve(__dirname, 'src/client/public');
var APP_DIR = path.resolve(__dirname, 'src/client/app');
var config = {
  entry: APP_DIR + '/index.jsx',
  output: {
    path: BUILD_DIR,
    filename: 'bundle.js'
  },
  module : {
    loaders : [
      {
        test : /\.jsx?/,
        include : APP_DIR,
        loader : 'babel-loader'
      }
    ]
  }
};
module.exports = config;
"

babelrc='
{
  "presets" : ["es2015", "react"]
}
'

package_json='
{
  "name": "react_environment",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack -d --watch",
    "build" : "webpack -p"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "",
  "license": "ISC",
  "homepage": "",
  "dependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "webpack": "^2.4.1"
  },
  "devDependencies": {}
}
'

echo React Environment Init Script

echo What is the name of your project?
read proj_name
cd $dev_directory
mkdir $proj_name
cd $proj_name
touch package.json
echo $package_json > package.json
npm install

# Webpack
touch webpack.config.js
echo $webpack_config > webpack.config.js

#babel
touch .babelrc
echo $babelrc > .babelrc

#Create dir trees and entry points
mkdir -p src/client/app
mkdir -p src/client/public
touch src/client/app/index.jsx
touch src/client/index.html
echo $index_html > src/client/index.html
echo $index_jsx > src/client/app/index.jsx
npm run dev &
cd src/client
python -m SimpleHTTPServer 8000#!/bin/bash


